# Generated by Django 3.1.6 on 2021-06-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='book_name',
            new_name='desc',
        ),
    ]
